require 'rake'

task :default do
  begin
    sh 'alloy compile'
    sh 'alloy run'
    sh 'touch ' + File.dirname(__FILE__) + '/../Resources/.gitkeep'
  rescue
    puts '======================================================'
    puts 'Failed'
    puts '======================================================'
  end
end
