require 'rake'

task :default do
  begin
    sh 'alloy compile'
    sh 'alloy run'
    sh 'touch ' + File.dirname(__FILE__) + '/../Resources/.gitkeep'
  rescue
    puts '======================================================'
    puts '                       Failed                         '
    puts '======================================================'
  end
end

task :andy do
  begin
    sh 'alloy compile --config platform=android'
    sh 'alloy run ../ android'
    sh 'touch ' + File.dirname(__FILE__) + '/../Resources/.gitkeep'
  rescue
    puts '======================================================'
    puts '                       Failed                         '
    puts '======================================================'
  end
end

task :clean do
  sh 'rm -rf ' + File.dirname(__FILE__) + '/../Resources/*'
end
